name: Rust Stable on macOS

on:
  schedule:
    - cron: '0 0 * * 6'

jobs:
  check:
    name: Check
    runs-on: macOS-latest
    strategy:
      matrix:
        rust:
          - stable
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Rust Version
        run: rustc --version
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
      matrix:
        rust:
          - stable
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Rust Version
        run: rustc --version
      - name: Run cargo test
        run: cargo test
